# ----------------------------------------------------------------------------
# Pure QAA Pitts test config
# ----------------------------------------------------------------------------

datamodule:
  train_set_name: "gsv-cities"
  cities: "all"
  train_image_size:
    - 280
    - 280
  val_image_size:
    - 322
    - 322
  img_per_place: 4
  batch_size: 40
  num_workers: 8
  val_set_names:
    - "pitts30k-test"
    - "pitts250k-test"

backbone:
  module: src.models.backbones
  class: DinoV2
  params:
    backbone_name: "dinov2_vitb14"
    num_unfrozen_blocks: 2
    return_cls_token: false

aggregator:
  module: src.models.aggregators.qaa_only
  class: QAAOnlyLayer
  params:
    in_channels: 768
    num_clusters: 64
    cluster_dim: 128
    token_dim: 0
    dropout: 0.0
    num_queries: 256
    self_attn: "both"
    dust_bin: true
    feature_nheads: 8
    score_nheads: 8
    attn_arch: "conv"
    skip_connection: "none"
    out_norm: true
    self_attn_out_norm: true
    score_norm: "ot"
    intra_norm: true
    eps: 1e-6

loss_function:
  module: src.losses
  class: VPRLossFunction
  params:
    loss_fn_name: "MultiSimilarityLoss"
    miner_name: "MultiSimilarityMiner"

trainer:
  optimizer: adamw
  lr: 0.0001
  wd: 0.001
  warmup: 6000
  max_epochs: 40
  milestones:
    - 10
    - 20
    - 30
  lr_mult: 0.1

train: false
ckpt_path: /root/code/global/OpenVPRLab/logs/dinov2_vitb14/QAAOnlyLayer/version_0/checkpoints/epoch(22)_step(35949)_R1[0.9311]_R5[0.9595].ckpt
