"""
OT-GaussVLAD with self-attentive Gaussian query codebook and token refinement.

This variant implements a conservative image-side refinement before estimating
mu_hat/sigma_hat:

    local tokens -> lightweight self-attention refinement -> OT assignment
    -> [mu_hat - mu, sigma_hat - sigma].

The reference Gaussian codebook is still generated by the self-attentive global
Gaussian queries from OTGaussVLADGaussianQueryCodebookLayer. The new token
refinement branch is residual and small-scale by default, so the model starts
close to the original Gaussian query codebook baseline.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

from .ot_gaussvlad_gaussian_query_codebook import (
    OTGaussVLADGaussianQueryCodebookLayer,
    inverse_sigmoid,
)

__all__ = ["OTGaussVLADGaussianQueryCodebookTokenRefineLayer"]


class LocalTokenSelfAttentionRefinement(nn.Module):
    """Pre-norm residual self-attention for local tokens."""

    def __init__(
        self,
        embed_dim: int,
        num_heads: int = 4,
        dropout: float = 0.0,
        mlp_ratio: float = 2.0,
        use_ffn: bool = True,
        out_norm: bool = False,
        residual_scale_init: float = 0.05,
        max_residual_scale: float = 1.0,
    ):
        super().__init__()
        embed_dim = int(embed_dim)
        num_heads = int(num_heads)
        max_residual_scale = float(max_residual_scale)
        residual_scale_init = float(residual_scale_init)

        if embed_dim % num_heads != 0:
            raise ValueError("embed_dim must be divisible by num_heads.")
        if max_residual_scale <= 0:
            raise ValueError("max_residual_scale must be positive.")
        if not 0.0 < residual_scale_init < max_residual_scale:
            raise ValueError("residual_scale_init must be in (0, max_residual_scale).")

        self.max_residual_scale = max_residual_scale
        self.use_ffn = bool(use_ffn)
        self.out_norm_flag = bool(out_norm)

        self.attn_norm = nn.LayerNorm(embed_dim)
        self.self_attn = nn.MultiheadAttention(
            embed_dim=embed_dim,
            num_heads=num_heads,
            dropout=float(dropout),
            batch_first=True,
        )
        self.dropout = nn.Dropout(float(dropout)) if dropout > 0 else nn.Identity()

        if self.use_ffn:
            hidden_dim = max(embed_dim, int(round(embed_dim * float(mlp_ratio))))
            self.ffn_norm = nn.LayerNorm(embed_dim)
            self.ffn = nn.Sequential(
                nn.Linear(embed_dim, hidden_dim),
                nn.GELU(),
                nn.Dropout(float(dropout)) if dropout > 0 else nn.Identity(),
                nn.Linear(hidden_dim, embed_dim),
                nn.Dropout(float(dropout)) if dropout > 0 else nn.Identity(),
            )
        else:
            self.ffn_norm = None
            self.ffn = None

        self.out_norm = nn.LayerNorm(embed_dim) if self.out_norm_flag else nn.Identity()
        scale_ratio = residual_scale_init / max_residual_scale
        self.residual_scale_logit = nn.Parameter(torch.tensor(inverse_sigmoid(scale_ratio)))

    def residual_scale(self) -> torch.Tensor:
        return self.max_residual_scale * torch.sigmoid(self.residual_scale_logit)

    def forward(self, tokens: torch.Tensor) -> torch.Tensor:
        scale = self.residual_scale().to(dtype=tokens.dtype, device=tokens.device)

        attn_in = self.attn_norm(tokens)
        attn_out = self.self_attn(attn_in, attn_in, attn_in, need_weights=False)[0]
        tokens = tokens + scale * self.dropout(attn_out)

        if self.use_ffn:
            tokens = tokens + scale * self.ffn(self.ffn_norm(tokens))

        return self.out_norm(tokens)


class OTGaussVLADGaussianQueryCodebookTokenRefineLayer(OTGaussVLADGaussianQueryCodebookLayer):
    """
    Scheme A: refine image local tokens before OT Gaussian moment estimation.

    Compared with OTGaussVLADGaussianQueryCodebookLayer, the only extra step is:
        local = token_refiner(local)

    before token-mass prediction, Gaussian scoring, Sinkhorn transport, and
    mu_hat/sigma_hat computation. The output descriptor dimension is unchanged:
        num_clusters * 2 * cluster_dim.
    """

    def __init__(
        self,
        *args,
        token_refine_nheads=4,
        token_refine_dropout=0.0,
        token_refine_mlp_ratio=2.0,
        token_refine_use_ffn=True,
        token_refine_out_norm=False,
        token_refine_scale_init=0.05,
        token_refine_max_residual_scale=1.0,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)

        self.token_refiner = LocalTokenSelfAttentionRefinement(
            embed_dim=self.cluster_dim,
            num_heads=int(token_refine_nheads),
            dropout=float(token_refine_dropout),
            mlp_ratio=float(token_refine_mlp_ratio),
            use_ffn=bool(token_refine_use_ffn),
            out_norm=bool(token_refine_out_norm),
            residual_scale_init=float(token_refine_scale_init),
            max_residual_scale=float(token_refine_max_residual_scale),
        )

    def _refine_local_tokens(self, local: torch.Tensor) -> torch.Tensor:
        tokens = local.transpose(1, 2).contiguous()  # [B, N, D]
        tokens = self.token_refiner(tokens)
        return tokens.transpose(1, 2).contiguous()  # [B, D, N]

    def forward(self, x):
        x = self._split_backbone_output(x)
        local = self._extract_local_tokens(x)  # [B, D, N]
        local = self._refine_local_tokens(local)
        token_mass = self._compute_token_mass(local)  # [B, N]
        mu, log_sigma = self._gaussian_codebook()

        if self.score_mode == "gmm":
            logits = self._gmm_scores(local)
        else:
            logits = self._attention_scores(local)

        assignments = self._transport(logits, token_mass)  # [B, K, N]
        cluster_mass = assignments.sum(dim=-1, keepdim=True)  # [B, K, 1]
        gamma = assignments / cluster_mass.clamp_min(self.eps)

        mu_hat = torch.einsum("bkn,bdn->bkd", gamma, local)
        second_moment = torch.einsum("bkn,bdn->bkd", gamma, local.square())
        var_hat = (second_moment - mu_hat.square()).clamp_min(self.eps)
        sigma_hat = torch.sqrt(var_hat)

        mean_shift = mu_hat - mu.unsqueeze(0)
        sigma_shift = sigma_hat - torch.exp(log_sigma).clamp_min(self.eps).unsqueeze(0)

        if self.mass_preserving:
            mass_weight = cluster_mass * (self.num_clusters / max(1.0 - self.dustbin_mass, self.eps))
            mass_weight = mass_weight.clamp_min(self.eps).pow(self.mass_power)
            mean_shift = mean_shift * mass_weight
            sigma_shift = sigma_shift * mass_weight

        residual = torch.cat([mean_shift, sigma_shift], dim=-1)
        descriptor = residual.reshape(local.size(0), -1)
        return F.normalize(descriptor, p=2, dim=-1)
